name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdzenie repozytorium
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ustawienie Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Instalacja pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Instalacja zależności
        run: pnpm install

      - name: Uruchomienie Prettiera
        run: pnpm run format

      - name: Uruchomienie ESLinta
        run: pnpm run lint

      - name: Uruchomienie testów jednostkowych
        run: pnpm run test