name: CI

on:
  push:
    branches:
      - '**'  # sprawdza wszystkie gałęzie
  pull_request:
    branches:
      - '**'  # sprawdza PR do wszystkich gałęzi

jobs:
  quality:
    name: Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm nx format:check --all

      - name: Run ESLint
        run: pnpm nx affected:lint

      - name: Run unit tests
        run: pnpm nx affected:test
