name: PR Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: pnpm install

    - name: Set up Nx Cloud
      run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

    - name: Determine affected projects
      id: affected
      run: |
        AFFECTED=$(npx nx print-affected --select=projects --base=origin/master)
        echo "affected=$AFFECTED" >> $GITHUB_OUTPUT

    - name: Run Prettier
      run: npx nx format:check --base=origin/master

    - name: Run Lint
      run: npx nx affected:lint --base=origin/master

    - name: Run Tests
      run: npx nx affected:test --base=origin/master

    - name: Stop Nx Cloud agents
      run: npx nx-cloud stop-all-agents
      if: always()